### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by diosney** [khan4019/tree-grid-directive#16]
Hi,

The following styles are causing that the grid really looks bad on Bootstrap 3:

```css
 .tree-grid .tree-grid-row {  
  padding: 0px;
  margin:0px;
}
.tree-grid .tree-grid-row td {
    padding: 1px;
    margin:0px;
}

.tree-grid .tree-grid-row a {
  padding: 3px 10px;
}
```

The following images are when removing the styles (after) and when they are present (before).

Before:
![styles before](https://cloud.githubusercontent.com/assets/1340074/4120100/c9995e76-32af-11e4-9b45-1184eb29e364.png)

After:
![styles after](https://cloud.githubusercontent.com/assets/1340074/4120099/c9110850-32af-11e4-8b12-34b782f458c5.png)
